### PR TITLE
Changed icon

### PR DESCRIPTION
**Pull request by shruti512**

### CODE REVIEW

**Comment by shruti512** [comment]
Hey, can you add "hacktoberfest" topic in about section of this repo so the PRs can be eligible? They have changed some rules.

**Comment by Ujjwal3009** [comment]
Hey @shruti512 can you make a  navbar for this app?

**Comment by shruti512** [comment]
I will try it. Can you add "hacktoberfest" topic in about section of this repo so the PRs can be eligible? They have changed some rules

**Comment by Ujjwal3009** [comment]
okay

**Pull request merged**
